scrape_configs:
  - job_name: SpringAuth
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets: ["92.206.107.36:8080"]
        labels:
          application: "SpringAuth"