name: GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      loki:
        image: grafana/loki
        ports:
          - "3100:3100"
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4
      - name: JDK Repo
        uses: actions/setup-java@v4
        with:
            distribution: 'oracle'
            java-version: '21'
      - name: Mvn package
        run: mvn -DLOKI_URL=http://localhost:3100 clean install
  test:
    runs-on: ubuntu-latest
    services:
      loki:
        image: grafana/loki
        ports:
          - "3100:3100"
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4
      - name: JDK Repo
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Mvn package
        run: mvn -DLOKI_URL=http://localhost:3100 clean install
      - name: Run Tests
        run: mvn -DLOKI_URL=http://localhost:3100 test